//
//  BALicensesCellNode.swift
//  Bais
//
//  Created by Jonathan Bursztyn on 9/2/17.
//  Copyright © 2017 Board Social, Inc. All rights reserved.
//

import Foundation
import AsyncDisplayKit

protocol BALicensesNodeDelegate: class {
	func licensesNodeDidClickLicenseButton(_ button: BALicensesButtonElementCellNode)
}

class BALicensesCellNode: ASCellNode{
	
	let popNode = BALicensesButtonElementCellNode(productName: "pop", license: "BSD License\r\n\r\nFor Pop software\r\n\r\nCopyright (c) 2014, Facebook, Inc. All rights reserved.\r\n\r\nRedistribution and use in source and binary forms, with or without modification,\r\nare permitted provided that the following conditions are met:\r\n\r\n * Redistributions of source code must retain the above copyright notice, this\r\n   list of conditions and the following disclaimer.\r\n\r\n * Redistributions in binary form must reproduce the above copyright notice,\r\n   this list of conditions and the following disclaimer in the documentation\r\n   and/or other materials provided with the distribution.\r\n\r\n * Neither the name Facebook nor the names of its contributors may be used to\r\n   endorse or promote products derived from this software without specific\r\n   prior written permission.\r\n\r\nTHIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS \"AS IS\" AND\r\nANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED\r\nWARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE\r\nDISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR\r\nANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES\r\n(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;\r\nLOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON\r\nANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT\r\n(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS\r\nSOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.")
	let dgActivityNode = BALicensesButtonElementCellNode(productName: "DGActivityIndicatorView", license: "The MIT License (MIT)\r\n\r\nCopyright (c) 2015 Danil Gontovnik\r\n\r\nPermission is hereby granted, free of charge, to any person obtaining a copy\r\nof this software and associated documentation files (the \"Software\"), to deal\r\nin the Software without restriction, including without limitation the rights\r\nto use, copy, modify, merge, publish, distribute, sublicense, and/or sell\r\ncopies of the Software, and to permit persons to whom the Software is\r\nfurnished to do so, subject to the following conditions:\r\n\r\nThe above copyright notice and this permission notice shall be included in all\r\ncopies or substantial portions of the Software.\r\n\r\nTHE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\r\nIMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\r\nFITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\r\nAUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\r\nLIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\r\nOUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE\r\nSOFTWARE.")
	let asdkNode = BALicensesButtonElementCellNode(productName: "AsyncDisplayKit", license: "BSD License\r\n\r\nFor AsyncDisplayKit software\r\n\r\nCopyright (c) 2014-present, Facebook, Inc. All rights reserved.\r\n\r\nRedistribution and use in source and binary forms, with or without modification,\r\nare permitted provided that the following conditions are met:\r\n\r\n * Redistributions of source code must retain the above copyright notice, this\r\n   list of conditions and the following disclaimer.\r\n\r\n * Redistributions in binary form must reproduce the above copyright notice,\r\n   this list of conditions and the following disclaimer in the documentation\r\n   and/or other materials provided with the distribution.\r\n\r\n * Neither the name Facebook nor the names of its contributors may be used to\r\n   endorse or promote products derived from this software without specific\r\n   prior written permission.\r\n\r\nTHIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS \"AS IS\" AND\r\nANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED\r\nWARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE\r\nDISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR\r\nANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES\r\n(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;\r\nLOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON\r\nANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT\r\n(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS\r\nSOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.")
	let tabBarNode = BALicensesButtonElementCellNode(productName: "ESTabBarController", license: "The MIT License (MIT)\r\n\r\nCopyright (c) 2016 lihao\r\n\r\nPermission is hereby granted, free of charge, to any person obtaining a copy\r\nof this software and associated documentation files (the \"Software\"), to deal\r\nin the Software without restriction, including without limitation the rights\r\nto use, copy, modify, merge, publish, distribute, sublicense, and/or sell\r\ncopies of the Software, and to permit persons to whom the Software is\r\nfurnished to do so, subject to the following conditions:\r\n\r\nThe above copyright notice and this permission notice shall be included in all\r\ncopies or substantial portions of the Software.\r\n\r\nTHE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\r\nIMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\r\nFITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\r\nAUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\r\nLIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\r\nOUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.")
	let fbsdkCoreNode = BALicensesButtonElementCellNode(productName: "FBSDKCoreKit", license: "Copyright (c) 2014-present, Facebook, Inc. All rights reserved.\r\n\r\nYou are hereby granted a non-exclusive, worldwide, royalty-free license to use,\r\ncopy, modify, and distribute this software in source code or binary form for use\r\nin connection with the web services and APIs provided by Facebook.\r\n\r\nAs with any software that integrates with the Facebook platform, your use of\r\nthis software is subject to the Facebook Developer Principles and Policies\r\n[http://developers.facebook.com/policy/]. This copyright notice shall be\r\nincluded in all copies or substantial portions of the software.\r\n\r\nTHE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\r\nIMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS\r\nFOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR\r\nCOPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER\r\nIN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN\r\nCONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.")
	let fbsdkLoginNode = BALicensesButtonElementCellNode(productName: "FBSDKLoginKit", license: "Copyright (c) 2014-present, Facebook, Inc. All rights reserved.\r\n\r\nYou are hereby granted a non-exclusive, worldwide, royalty-free license to use,\r\ncopy, modify, and distribute this software in source code or binary form for use\r\nin connection with the web services and APIs provided by Facebook.\r\n\r\nAs with any software that integrates with the Facebook platform, your use of\r\nthis software is subject to the Facebook Developer Principles and Policies\r\n[http://developers.facebook.com/policy/]. This copyright notice shall be\r\nincluded in all copies or substantial portions of the software.\r\n\r\nTHE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\r\nIMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS\r\nFOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR\r\nCOPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER\r\nIN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN\r\nCONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.")
	let fbsdkShareNode = BALicensesButtonElementCellNode(productName: "FBSDKShareKit", license: "Copyright (c) 2014-present, Facebook, Inc. All rights reserved.\r\n\r\nYou are hereby granted a non-exclusive, worldwide, royalty-free license to use,\r\ncopy, modify, and distribute this software in source code or binary form for use\r\nin connection with the web services and APIs provided by Facebook.\r\n\r\nAs with any software that integrates with the Facebook platform, your use of\r\nthis software is subject to the Facebook Developer Principles and Policies\r\n[http://developers.facebook.com/policy/]. This copyright notice shall be\r\nincluded in all copies or substantial portions of the software.\r\n\r\nTHE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\r\nIMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS\r\nFOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR\r\nCOPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER\r\nIN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN\r\nCONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.")
	let alamoNode = BALicensesButtonElementCellNode(productName: "Alamofire", license: "Copyright (c) 2014-2016 Alamofire Software Foundation (http://alamofire.org/)\r\n\r\nPermission is hereby granted, free of charge, to any person obtaining a copy\r\nof this software and associated documentation files (the \"Software\"), to deal\r\nin the Software without restriction, including without limitation the rights\r\nto use, copy, modify, merge, publish, distribute, sublicense, and/or sell\r\ncopies of the Software, and to permit persons to whom the Software is\r\nfurnished to do so, subject to the following conditions:\r\n\r\nThe above copyright notice and this permission notice shall be included in\r\nall copies or substantial portions of the Software.\r\n\r\nTHE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\r\nIMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\r\nFITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\r\nAUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\r\nLIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\r\nOUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN\r\nTHE SOFTWARE.")
	let swiftyNode = BALicensesButtonElementCellNode(productName: "SwiftyJSON", license: "The MIT License (MIT)\r\n\r\nCopyright (c) 2017 Ruoyu Fu\r\n\r\nPermission is hereby granted, free of charge, to any person obtaining a copy\r\nof this software and associated documentation files (the \"Software\"), to deal\r\nin the Software without restriction, including without limitation the rights\r\nto use, copy, modify, merge, publish, distribute, sublicense, and/or sell\r\ncopies of the Software, and to permit persons to whom the Software is\r\nfurnished to do so, subject to the following conditions:\r\n\r\nThe above copyright notice and this permission notice shall be included in\r\nall copies or substantial portions of the Software.\r\n\r\nTHE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\r\nIMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\r\nFITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\r\nAUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\r\nLIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\r\nOUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN\r\nTHE SOFTWARE.")
	let promiseNode = BALicensesButtonElementCellNode(productName: "PromiseKit", license: "Copyright 2016, Max Howell; mxcl@me.com\r\n\r\nPermission is hereby granted, free of charge, to any person obtaining a\r\ncopy of this software and associated documentation files (the\r\n\"Software\"), to deal in the Software without restriction, including\r\nwithout limitation the rights to use, copy, modify, merge, publish,\r\ndistribute, sublicense, and/or sell copies of the Software, and to\r\npermit persons to whom the Software is furnished to do so, subject to\r\nthe following conditions:\r\n\r\nThe above copyright notice and this permission notice shall be included\r\nin all copies or substantial portions of the Software.\r\n\r\nTHE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS\r\nOR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF\r\nMERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.\r\nIN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY\r\nCLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,\r\nTORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE\r\nSOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.")
	let countryNode = BALicensesButtonElementCellNode(productName: "CountryPicker", license: "CountryPicker\r\n\r\nVersion 1.3, September 30th, 2016\r\n\r\nCopyright (C) 2011 Charcoal Design\r\n\r\nThis software is provided 'as-is', without any express or implied warranty. In no event will the authors be held liable for any damages arising from the use of this software.\r\n\r\nThe source code and data files in this project are the sole creation of Charcoal Design and are free for use subject to the terms below. The flag icons were sourced from https://github.com/koppi/iso-country-flags-svg-collection and are available under a Public Domain license\r\n\r\nPermission is granted to anyone to use this software for any purpose, including commercial applications, and to alter it and redistribute it freely, subject to the following restrictions:\r\n\r\nThe origin of this software must not be misrepresented; you must not claim that you wrote the original software. If you use this software in a product, an acknowledgment in the product documentation would be appreciated but is not required.\r\n\r\nAltered source versions must be plainly marked as such, and must not be misrepresented as being the original software.\r\n\r\nThis notice may not be removed or altered from any source distribution.")
	let nmessengerNode = BALicensesButtonElementCellNode(productName: "NMessenger", license: "MIT License\r\n\r\nCopyright (c) 2016 eBay Software Foundation\r\nInitially written by Aaron Tainter and David Schecter\r\n\r\nPermission is hereby granted, free of charge, to any person obtaining a copy\r\nof this software and associated documentation files (the \"Software\"), to deal\r\nin the Software without restriction, including without limitation the rights\r\nto use, copy, modify, merge, publish, distribute, sublicense, and/or sell\r\ncopies of the Software, and to permit persons to whom the Software is\r\nfurnished to do so, subject to the following conditions:\r\n\r\nThe above copyright notice and this permission notice shall be included in all\r\ncopies or substantial portions of the Software.\r\n\r\nTHE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\r\nIMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\r\nFITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\r\nAUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\r\nLIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\r\nOUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE\r\nSOFTWARE.")
	let iconsNode = BALicensesButtonElementCellNode(productName: "Icons8", license: "Icons by https://icons8.com/")
	let geofireNode = BALicensesButtonElementCellNode(productName: "GeoFire", license: "The MIT License (MIT)\r\n\r\nCopyright (c) 2016 Firebase\r\n\r\nPermission is hereby granted, free of charge, to any person obtaining a copy\r\nof this software and associated documentation files (the \"Software\"), to deal\r\nin the Software without restriction, including without limitation the rights\r\nto use, copy, modify, merge, publish, distribute, sublicense, and/or sell\r\ncopies of the Software, and to permit persons to whom the Software is\r\nfurnished to do so, subject to the following conditions:\r\n\r\nThe above copyright notice and this permission notice shall be included in all\r\ncopies or substantial portions of the Software.\r\n\r\nTHE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\r\nIMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\r\nFITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\r\nAUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\r\nLIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\r\nOUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE\r\nSOFTWARE.")
	
	weak var delegate: BALicensesNodeDelegate?
	
	required override init() {
		super.init()
		
		popNode.addTarget(self, action: #selector(licensePressed(_:)), forControlEvents: .touchUpInside)
		dgActivityNode.addTarget(self, action: #selector(licensePressed(_:)), forControlEvents: .touchUpInside)
		asdkNode.addTarget(self, action: #selector(licensePressed(_:)), forControlEvents: .touchUpInside)
		tabBarNode.addTarget(self, action: #selector(licensePressed(_:)), forControlEvents: .touchUpInside)
		fbsdkCoreNode.addTarget(self, action: #selector(licensePressed(_:)), forControlEvents: .touchUpInside)
		fbsdkLoginNode.addTarget(self, action: #selector(licensePressed(_:)), forControlEvents: .touchUpInside)
		fbsdkShareNode.addTarget(self, action: #selector(licensePressed(_:)), forControlEvents: .touchUpInside)
		alamoNode.addTarget(self, action: #selector(licensePressed(_:)), forControlEvents: .touchUpInside)
		swiftyNode.addTarget(self, action: #selector(licensePressed(_:)), forControlEvents: .touchUpInside)
		promiseNode.addTarget(self, action: #selector(licensePressed(_:)), forControlEvents: .touchUpInside)
		countryNode.addTarget(self, action: #selector(licensePressed(_:)), forControlEvents: .touchUpInside)
		nmessengerNode.addTarget(self, action: #selector(licensePressed(_:)), forControlEvents: .touchUpInside)
		iconsNode.addTarget(self, action: #selector(licensePressed(_:)), forControlEvents: .touchUpInside)
		geofireNode.addTarget(self, action: #selector(licensePressed(_:)), forControlEvents: .touchUpInside)

		addSubnode(popNode)
		addSubnode(dgActivityNode)
		addSubnode(asdkNode)
		addSubnode(tabBarNode)
		addSubnode(fbsdkCoreNode)
		addSubnode(fbsdkLoginNode)
		addSubnode(fbsdkShareNode)
		addSubnode(alamoNode)
		addSubnode(swiftyNode)
		addSubnode(promiseNode)
		addSubnode(countryNode)
		addSubnode(nmessengerNode)
		addSubnode(iconsNode)
		addSubnode(geofireNode)
	}
	
	func licensePressed(_ button: BALicensesButtonElementCellNode){
		delegate?.licensesNodeDidClickLicenseButton(button)
	}
	
	override func layoutSpecThatFits(_ constrainedSize: ASSizeRange) -> ASLayoutSpec {
		let verticalStack = ASStackLayoutSpec()
		verticalStack.direction = .vertical
		verticalStack.alignItems = .start
		verticalStack.children = [alamoNode, asdkNode, countryNode, dgActivityNode, tabBarNode, fbsdkCoreNode, fbsdkLoginNode, fbsdkShareNode, geofireNode, iconsNode, nmessengerNode, promiseNode, swiftyNode, popNode]
		return verticalStack
	}
}
